### ISSUE TITLE
Can't parse midi file that I create

### ISSUE THREAD

**Issue by adamhub** [Cornerback24/Blender-NLA-Midi-Copier#1]
Hey, love the addon!

I am trying to figure out what I have done wrong. I took your testMidiFile.mid and edited in Musescore3 to have just one part. The file I export is can no longer be read by the Python-Midi-Analysis lib. I get the following error:

  ` ...
    midiData = MidiData(midi_file)
  File ".../MidiData.py", line 51, in __init__
    event = self.eventDecoder.nextEvent()
  File ".../MidiEventDecoder.py", line 28, in nextEvent
    return self.midiEvent(self.midiParser.readNextData())
  File ".../MidiEventDecoder.py", line 65, in midiEvent
    midiData = self.lastChannelStatusByte + midiData
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
`
It's the same for a file I create from scratch in Musescore and Reaper too. Is there something I should change? I have attached the midi for reference. 

[testMidiFile3.zip](https://github.com/Cornerback24/Blender-NLA-Midi-Copier/files/3469809/testMidiFile3.zip)

**Comment by Cornerback24** [comment]
Hey, glad you like the addon! This looks like an issue with midi parser, not anything you're doing wrong. I'm looking into it.

**Comment by Cornerback24** [comment]
I've fixed an issue with the midi parser, it should work with your midi file now :).

**Comment by adamhub** [comment]
Right on. Much appreciated.
