### ISSUE TITLE
Can’t use exported midi from Ableton

### ISSUE THREAD

**Issue by supermerger** [Cornerback24/Blender-NLA-Midi-Copier#3]
Not sure if this is the right place to raise this issue, but I’m sure that many users of this plugin will run into this exact issue eventually.

[Ableton only exports as SMF0](https://help.ableton.com/hc/en-us/articles/209068169-Understanding-MIDI-files)

Blender NLA does not work with SMF0.

I’ve looked around like crazy and I can’t find any useful midi-type converters. I managed to make one using the demo version of "Sweet Midi Convertor" but I ran into the issue "Could not load midi file: 'SequencerSpecificEvent' object has no attribute 'setDeltaTimeFromBytes' " so the header in the midi file probably wasn’t written correctly.
 
From what I can see the main difference is that the tempo is encoded into the SMF1 files. Perhaps there could be a box in which to put in the tempo manually so that the header on the SMF1 would be encoded properly through python in Blender? Basically I’m not smart enough to do this myself. Honestly most of the above is just rambling and guessing.

**Comment by Cornerback24** [comment]
Thanks for bringing this up. If Ableton only exports SMF0, it'll probably be worth looking into adding SMF0 support to the plugin. Can you provide sample midi files from Ableton? 

Also maybe a file that is causing the loading error you mentioned? I think that is an issue with the plugin, not the midi file. If you want to try a quick fix in the code, try replacing "class SequencerSpecificEvent:" in MidiEvents.py with "class SequencerSpecificEvent(MetaEvent):" (forgot to extend the event class, will try to get that fix in today).  

I think the biggest difference between SMF0 and SMF1 as far as this plugin goes is that SMF1 separates different instruments into midi "Tracks", which the plugin is currently relying on to tell what instrument is what. In SMF0 everything is on only one track, but may be separated by channel. Tempo should be in all midi files as far as I know, but adding a tempo overwrite could be useful anyway. 

I don't know much about Ableton and don't have Ableton myself. Does Ableton allow you to export multiple instruments in one midi file? If so it would be helpful to have an example file with multiple instruments (as well as an example with only one instrument).

**Comment by supermerger** [comment]
Ableton export of midi files is very basic and allows one clip, one track at a time. 

Attached are a few midi tracks taken directly from Ableton

Hope they help! I haven’t had a chance to try the fixes you suggested, but I will look in the morning

[midi_test_files_SEPT20.zip](https://github.com/Cornerback24/Blender-NLA-Midi-Copier/files/5263694/midi_test_files_SEPT20.zip)

**Comment by Cornerback24** [comment]
Thanks for the midi files! Looks like you were right about no tempo information in them. 
The plugin should now be able to load SMF0 files (if the file is SMF0, it will only create one track will all the notes). There are now options to change the tempo in the Midi Settings panel.
