### ISSUE TITLE
3.2 version

### ISSUE THREAD

**Issue by soroko77** [Cornerback24/Blender-NLA-Midi-Copier#9]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blender-NLA-Midi-Copier-0'

**Comment by Cornerback24** [comment]
It seems like the folder the addon is in has changed and Blender is looking for the old folder (don't know what would have changed it). Try
- Go to your blender addon preferences
- Disable 'Blender-NLA-Midi-Copier-0' if it is there (It might say something about a missing script file)
- Find Blender NLA Midi Copier and enable it (If you can't find it try reinstalling the addon)

**Comment by Cornerback24** [comment]
Let me know if this is still happening after following those steps. Not sure if there's anything I can change in the add-on because Blender's add-on import code is not part of it.
